In [1]:
import pandas as pd
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
file_path = '/content/drive/MyDrive/data.csv'

In [3]:
try:
    # CSV 파일 읽기
    # skiprows=2: 첫 두 줄(헤더 및 빈 줄)을 건너뛰고 세 번째 줄부터 데이터로 인식
    # encoding='utf-8': 한글이 포함된 경우 인코딩 문제 방지
    df = pd.read_csv(file_path, skiprows=2, encoding='utf-8')

    # 필요한 컬럼만 선택
    # '대여소 번호'는 CSV 상에서 첫 번째 컬럼이므로 인덱스 0,
    # '위도'는 인덱스 4, '경도'는 인덱스 5에 해당합니다.
    # 컬럼명이 정확하다면 컬럼명으로 직접 접근하는 것이 더 명확합니다.
    # 여기서는 제공해주신 데이터 시작 줄의 헤더가 없으므로 인덱스로 접근합니다.
    # 만약 헤더가 '대여소 번호', '위도', '경도'로 명확하게 있다면 df[['대여소 번호', '위도', '경도']] 와 같이 사용할 수 있습니다.

    # 🚨 중요: 제공해주신 데이터는 첫 줄에 헤더가 있고 그 다음 두 줄이 비어 있습니다.
    # 따라서 skiprows=2를 하면 '00301'이 있는 줄부터 읽게 되며,
    # 이 줄을 pandas는 헤더로 인식하려고 할 수 있습니다.
    # 이를 방지하기 위해 header=None을 사용하여 헤더가 없음을 명시하고
    # 직접 컬럼 이름을 지정해주는 것이 안전합니다.
    df = pd.read_csv(file_path, skiprows=2, encoding='utf-8', header=None)

    # 컬럼명 지정 (편의를 위해)
    df.columns = ['대여소 번호', '보관소(대여소)명', '자치구', '상세주소', '위도', '경도']

    # '대여소 번호', '위도', '경도' 컬럼 선택
    station_data = df[['대여소 번호', '위도', '경도']]

    # 결과 확인
    print(station_data.head())

    # 모든 데이터 순회하며 출력 (예시)
    # for index, row in station_data.iterrows():
    #     print(f"대여소 번호: {row['대여소 번호']}, 위도: {row['위도']}, 경도: {row['경도']}")

except FileNotFoundError:
    print(f"오류: '{file_path}' 파일을 찾을 수 없습니다. 파일 경로를 확인해주세요.")
except Exception as e:
    print(f"데이터를 읽는 중 오류가 발생했습니다: {e}")

   대여소 번호       위도       경도
0     302  37.5759  126.974
1     303  37.5718  126.975
2     305  37.5726  126.978
3     307  37.5700  126.971
4     308  37.5700  126.974

In [4]:
try:
    # 이전에 제안했던 skiprows=2, header=None을 사용하여 다시 시도합니다.
    df = pd.read_csv(file_path, skiprows=2, encoding='utf-8', header=None)
    df.columns = ['대여소 번호', '보관소(대여소)명', '자치구', '상세주소', '위도', '경도']
    station_data = df[['대여소 번호', '위도', '경도']]

    # 데이터프레임의 총 행 수 출력
    print(f"로드된 총 대여소 데이터 수: {len(station_data)}")

    # 데이터프레임의 마지막 몇 개 행 출력 (데이터가 잘 로드되었는지 확인)
    print("\n데이터의 마지막 5행:")
    print(station_data.tail())

except FileNotFoundError:
    print(f"오류: '{file_path}' 파일을 찾을 수 없습니다. 파일 경로를 확인해주세요.")
except Exception as e:
    print(f"데이터를 읽는 중 오류가 발생했습니다: {e}")

로드된 총 대여소 데이터 수: 2761

데이터의 마지막 5행:
      대여소 번호       위도       경도
2756    3700  37.5482  127.123
2757    3701  37.5233  127.146
2758    4951  37.5480  127.135
2759    4952  37.5415  127.130
2760    4953  37.5335  127.141